### ISSUE TITLE
Link spells does not count as mutual link

### ISSUE THREAD

**Issue by luoxueyasha** [purerosefallen/ygopro#60]
Tested both link spell and link monsters changed type to link spell, both don't work properly in single mode, test by link summoning 代码破坏者·病毒狂战士/コードブレイカー・ウイルスバーサーカー(48736598) and tried to revive 代码破坏者·零日/コードブレイカー・ゼロデイ(8662794) in GY.
Also, do link magic those which link each other (eg. spellzone0→  ←spellzone1 ) count in mutual link?

Test environment: Koishipro 1.035.3 Himehina

**Comment by purerosefallen** [comment]
I have no idea how anime ruling works.
